"""First

Revision ID: 202bf8b04e02
Revises: 17d7722c9fc6
Create Date: 2022-02-03 13:51:04.374140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202bf8b04e02'
down_revision = '17d7722c9fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
