"""Added a foreign key for user

Revision ID: 49a941811ab8
Revises: e3d803e42daf
Create Date: 2022-02-03 14:11:46.298244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a941811ab8'
down_revision = 'e3d803e42daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
